### ISSUE TITLE
A question on menu main

### ISSUE THREAD

**Issue by ghost** [nirocfz/arabica#2]
Hi, a beginner here and I have faced an issue while trying to build a blog using arabica. For some reason it does not allow me to change the menu main. I was able to add some by doing [[menu.main]] on the config.toml but could not get rid of About Hugo, Getting Started, and Migrating from Jekyll from the original version. How could I modify them?

**Comment by bytes-crafter** [comment]
@jaehyunhan That's because there's `menu: main` in front matter of these posts (that's one of the ways to add menus, see [Menus](https://gohugo.io/content-management/menus/).), just remove this line, you'll get rid of them.
