### ISSUE TITLE
URL in the footer may be broken

### ISSUE THREAD

**Issue by mandarvaze** [nirocfz/arabica#6]
URL in the footer - http://thedarkroast.com/arabica is not accessible.

I confirmed using 
https://downforeveryoneorjustme.com/thedarkroast.com

Could be temporary, in which case feel free to close.

**Comment by alloydwhitlock** [comment]
Filed a pull request https://github.com/nirocfz/arabica/pull/9 to replace broken URL with the GitHub repository URL.

**Comment by mandarvaze** [comment]
Does this get deployed automatically (CI) ? Cause https://arabica.netlify.com/ still shows old/broken URL
